### ISSUE TITLE
All traffic blocked on Android

### ISSUE THREAD

**Issue by evilcoleslaw** [LiCybora/NanoCoreFirefox#20] opened 2019-06-17 20:34 UTC
### Describe the issue (Required)
Nothing at all loads when Nano Adblocker is enabled. No pages, search engines, etc except domains restricted for webextensions (addons.mozilla.org, etc) loads. Even updating filter lists within the addon doesn't work.

### Screenshots (Required)
![Screenshot_20190617-162751](https://user-images.githubusercontent.com/51482442/59650531-54f2f600-9154-11e9-9156-1c2e5110626d.png)

### Screenshot of console (Required, press `F12` to open the console)
Later if needed

### URLs where this issue occurs (Required if applicable)
All

### Reproduction Steps (Optional if trivial)

1. Install Nano Adblocker on Firefox for Android.

2. Attempt to load any page.

#### Environment (Required)

- Operating System and Version: Android P
- Browser and Version: 67.0.2 (Firefox for Android)
- Nano Adblocker Version: 1.0.0.116
- Nano Defender Version (Optional if you are not using it): n/a

#### Your filter lists (Required)

Default filters only

**Comment by LordDeimos666** [comment] 2019-06-18 00:08
Not only in Android, also on my 2 PC with windows 10 got the same problem. All traffic blocked unless I disable Nano AdBlocker

**Comment by afgks** [comment] 2019-06-18 10:44
Same. I have to disable Nano Adblocker on both Windows 10 and Android.

**Comment by LiCybora** [comment] 2019-06-19 04:11
The issue is likely related to #21, especially upgrading from previous version with Adguard filter enabled will cause this.

v1.0.0.117 is released. Can someone verify the fix? (I can no longer reproduce with latest version)

**Comment by evilcoleslaw** [comment] 2019-06-19 04:17
Yep, it's working properly now.

**Comment by LiCybora** [comment] 2019-06-19 04:20
Thanks. Closing as resolved.

**Closed as completed by LiCybora** 2019-06-19 04:20 UTC
Labels: bug, Fixed
