### ISSUE TITLE
[Breakage] forum.xda-developers.com

### ISSUE THREAD

**Issue by Cyberavater** [LiCybora/NanoCoreFirefox#31] opened 2020-05-13 15:38 UTC
Eg link: https://forum.xda-developers.com/showthread.php?t=2263392
OS: Android 9
Platform: Firefox (note this issue doesn't happen on the chromium-based browser)

Everything else is just default so, no point typing all that.
![Screenshot_20200513-213608](https://user-images.githubusercontent.com/32187927/81833854-09162000-9562-11ea-93dc-6e2e1800ee79.png)

Edit: Sorry, my bad. Everything else was not default, I had additional placeholder buster in Firefox, while it wasn't enabled on kiwi (Chromium-based browser). After enabling it in Kiwi it's happening there too, so it's NOT Firefox only issue.
I'm sorry again.

**Comment by LiCybora** [comment] 2020-05-15 12:35
@jspenguin2017

This rule in `Nano contrib filter – Placeholder buster` cause breakage.

`forum.xda-developers.com##.purchad:upward(1)`

**Comment by jspenguin2017** [comment] 2020-05-15 14:41
@LiCybora Can't reproduce. If this is a Firefox specific issue, contribution is required (open a PR to the contrib filters repository). 
![image](https://user-images.githubusercontent.com/7283682/82062758-d1a19380-9687-11ea-8c24-982de74a988f.png)

**Comment by Cyberavater** [comment] 2020-05-15 14:59
Edit: Sorry, my bad. Everything else was not default, I had additional placeholder buster in Firefox, while it wasn't enabled on kiwi (Chromium-based browser). After enabling it in Kiwi it's happening there too, so it's NOT Firefox only issue.
I'm sorry again. Tho @jspenguin2017 already added the filter so it seems to happen only in Android but not in PC I guess.

**Comment by jspenguin2017** [comment] 2020-05-15 15:03
Looks like it's mobile only.

**Comment by LiCybora** [comment] 2020-05-15 15:31
Yes mobile only. I should say it clearly...

Anyway closing as fixed.

**Closed as completed by LiCybora** 2020-05-15 15:31 UTC
Labels: Fixed, Android
