### ISSUE TITLE
When saving "My Filters" Nano Adblocker keeps scrolling to the end of the filters

### ISSUE THREAD

**Issue by sndcrde** [LiCybora/NanoCoreFirefox#37] opened 2020-10-05 18:54 UTC
### Describe the issue (Required)
Every time a change is made to "My Filters" (when a filter needs to be temporarily commented out, for example) Nano Adblocker keeps scrolling to the end of the filter list and one has to scroll back and find the place one was editing before. After a few saves like that it gets annoying pretty quick, especially if the filter list is long enough.

### URLs where this issue occurs (Required if applicable)
"My Filters" section of the Nano Adblocker

### Reproduction Steps (Optional if trivial)

1. Open the Nano Adblocker and go to the "My Filters" section. Create a filter list that takes several pages there.
2. Scroll to the beginning of the list and make a small change
3. Press the "Apply Changes" button or press Ctrl+S
4. You will see that Nano Adblocker will save the change but will also scroll to the bottom of the filter list thus losing the place where the edit was made. If one is testing something and has to repeatedly comment/uncomment the same filter in the middle of the list, the unrequested scroll to the bottom of the filter list is unnecessary and annoying.

#### Environment (Required)

- Operating System and Version: Debian 10 Buster
- Browser and Version: 78.3.0esr (64-bit)
- Nano Adblocker Version: 1.0.0.151
- Nano Defender Version (Optional if you are not using it): none

**Comment by sndcrde** [comment] 2020-10-13 20:42
I was hoping it would be fixed in 1.0.0.153. That's a pretty annoying bug, really surprised no one brought it up sooner.

**Comment by LiCybora** [comment] 2020-10-13 23:12
I am sorry to inform you that Nano Adblocker is no longer maintained. You may join the discussion [here](https://github.com/LiCybora/NanoDefenderFirefox/issues/187) for details. 1.0.0.154 will be the final version (not yet released but soon).

If the fix is trivial, I can include this bug fix. Otherwise, most likely will be a won't fix.

**Comment by sndcrde** [comment] 2020-10-14 00:38
Thanks, I understand your decision not to port for the new developers, whoever they are, as the situation with them does look quite shady.

No chance you would consider maintaining a separate and detached Firefox fork of NA? Thanks

**Comment by jspenguin2017** [comment] 2020-10-14 01:20
@LiCybora This is by design. But you're free to change it if you don't like it. The code is here: https://github.com/LiCybora/NanoCore2/blob/b93e33f0f57d261bfdaf77843f89bfd4c875cdf7/src/js/nano-editor.js#L628

**Comment by LiCybora** [comment] 2020-10-14 12:23
> No chance you would consider maintaining a separate and detached Firefox fork of NA? Thanks

For now, uBlock Origin is more mature and satisfy my need, and even available on Firefox mobile stable due to recommended by Mozilla where NA is not. Unless there is key feature I want but unavailable on uBlock Origin, I don't know the possible direction for development other than just pull upstream (uBO) update.

> The code is here: https://github.com/LiCybora/NanoCore2/blob/b93e33f0f57d261bfdaf77843f89bfd4c875cdf7/src/js/nano-editor.js#L628

Thanks. I will change it.

**Closed as completed** 2020-10-14 23:28 UTC
Labels: bug
